[project]
name = "aptreader"
version = "0.1.0"
description = "an APT repository scraper and browser"
readme = "README.md"
authors = [
    { name = "Andi Powers-Holmes", email = "aholmes@omnom.net" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
aptreader = "aptreader.app:main"

[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.14.7",
]
