[project]
name = "aptreader"
version = "0.1.0"
description = "an APT repository scraper and browser"
readme = "README.md"
authors = [
    { name = "Andi Powers-Holmes", email = "aholmes@omnom.net" }
]
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.12.5",
    "python-debian>=1.0.1",
    "reflex>=0.8.21",
    "typer>=0.20.0",
]

[project.scripts]
aptreader = "aptreader.app:app"

[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.14.7",
]


[tool.ruff]
# extend-exclude = ["static", "ci/templates"]
line-length = 110
src = ["src", "tests"]
target-version = "py313"

# Add rules to ban exec/eval
[tool.ruff.lint]
# 1. Enable flake8-bugbear (`B`) rules, in addition to the defaults.
select = ["E4", "E7", "E9", "F", "B"]
ignore = [
    "E501",
    "I001",
    "B905", # zip without explicit strict=
]
unfixable = ["B"]
extend-ignore = [ "I001"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "double"
